#!/bin/sh

program_fmc_vadj()
{
    #i2C bus0 switch select : PMBUS1(ch0)
    i2cset -f -y 0 0x74 0x01

    # VADJ_FMC output voltage settings
    i2ctransfer -f -y 0 w3@0x4E 0x40 0xf3 0x01
    i2ctransfer -f -y 0 w3@0x4E 0x42 0xf3 0x01
    #i2C bus0 switch select : PMBUS1(ch0)
    i2cset -f -y 0 0x74 0x01

    # VADJ_FMC output voltage settings
    i2ctransfer -f -y 0 w3@0x4E 0x40 0xf3 0x01
    i2ctransfer -f -y 0 w3@0x4E 0x42 0xf3 0x01
    i2ctransfer -f -y 0 w3@0x4E 0x43 0x00 0x00
    i2ctransfer -f -y 0 w3@0x4E 0x44 0x00 0x00
    i2ctransfer -f -y 0 w3@0x4E 0x21 0x80 0x01
    i2cset -f -y 0 0x4E 0x01 0x80
    
   echo ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>"
   echo "  FMC+ VADJ set to 1.5V by startup script  "
   echo "<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<"

}


echo "***********************************"
echo " Executing /usr/bin/startup-script "
echo "***********************************"

#
# The systemd service ensures that this script runs only
# after the EXT4 filesystem is mounted at /run/media/mmcblk0p2
#

target=/run/media/mmcblk0p2

if [ -d $target/lost+found ]; then
    mkdir -p  $target/work
    chmod 777 $target/work
    ln -s     $target/work /fs    
fi

target=/run/media/mmcblk0p2/release
if [ -f ${target}/system_update.sh ]; then
    chmod +x ${target}/system_update.sh
    ${target}/system_update.sh $target /run/media/mmcblk0p1
fi

ifconfig end0 12.12.12.12

# Set the FMC+ VADJ voltage to 1.5V
program_fmc_vadj

# Launch the bash-server
/utils/bash_server &

