#!/bin/sh

program_fmc_vadj()
{
    #i2C bus0 switch select : PMBUS1(ch0)
    i2cset -f -y 0 0x74 0x01

    # VADJ_FMC output voltage settings
    i2ctransfer -f -y 0 w3@0x4E 0x40 0xf3 0x01
    i2ctransfer -f -y 0 w3@0x4E 0x42 0xf3 0x01
    #i2C bus0 switch select : PMBUS1(ch0)
    i2cset -f -y 0 0x74 0x01

    # VADJ_FMC output voltage settings
    i2ctransfer -f -y 0 w3@0x4E 0x40 0xf3 0x01
    i2ctransfer -f -y 0 w3@0x4E 0x42 0xf3 0x01
    i2ctransfer -f -y 0 w3@0x4E 0x43 0x00 0x00
    i2ctransfer -f -y 0 w3@0x4E 0x44 0x00 0x00
    i2ctransfer -f -y 0 w3@0x4E 0x21 0x80 0x01
    i2cset -f -y 0 0x4E 0x01 0x80
    
   echo ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>"
   echo "  FMC+ VADJ set to 1.5V by startup script  "
   echo "<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<"
}


echo "***********************************"
echo " Executing /usr/bin/startup-script "
echo "***********************************"

# This is the partition where all our files of interest live
part=/run/media/mmcblk0p2

#
# The systemd service is supposed to ensures that this script 
# runs only after the EXT4 filesystem is mounted at
# /run/media/mmcblk0p2
#
# Sadly, this doesn't always work, so if we don't find it 
# mounted, we reboot to try again
#
test -d $part/lost+found     || reboot
test -d /run/media/mmcblk0p1 || reboot


# Create the writable workspace
mkdir -p  $part/work
chmod 777 $part/work
ln -s     $part/work /fs    

#
#  If there is a system_update script, run it!
#
target=$part/release
if [ -f ${target}/system_update.sh ]; then
    chmod +x ${target}/system_update.sh
    ${target}/system_update.sh $target /run/media/mmcblk0p1
fi

#
#  Here we configure the Ethernet interface to our
#  desired MAC address and IPv4 address
#
eth=end0
mac=$(cat $part/config/mac_address)
echo "Setting MAC address to $mac"
ifconfig $eth down
ifconfig $eth hw ether $mac
ifconfig $eth 12.12.12.12
ifconfig $eth up

#
# Install the SSH keys into /etc/ssh
#
echo "Installing SSH keys"
cp $part/config/ssh_host_ecdsa* /etc/ssh

# Set the FMC+ VADJ voltage to 1.5V
program_fmc_vadj

# Launch the bash-server
/utils/bash_server &

# Don't allow systemctl to generate ssh keys
systemctl stop sshdgenkeys

